Document: landing-zone
Title: Debian landing-zone Manual
Author: <insert document author here>
Abstract: This manual describes what landing-zone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/landing-zone/landing-zone.sgml.gz

Format: postscript
Files: /usr/share/doc/landing-zone/landing-zone.ps.gz

Format: text
Files: /usr/share/doc/landing-zone/landing-zone.text.gz

Format: HTML
Index: /usr/share/doc/landing-zone/html/index.html
Files: /usr/share/doc/landing-zone/html/*.html
